#!/usr/bin/env python3
"""Write a concise summary for generated special-profile update pull requests."""
from __future__ import annotations

import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SUMMARY_PATH = ROOT / "docs" / "GENERATED_UPDATE_SUMMARY.md"


def run_git(arguments: list[str]) -> subprocess.CompletedProcess[str]:
    return subprocess.run(["git", *arguments], cwd=ROOT, text=True, capture_output=True, check=False)


def inside_git_worktree() -> bool:
    result = run_git(["rev-parse", "--is-inside-work-tree"])
    return result.returncode == 0 and result.stdout.strip() == "true"


def git_output(arguments: list[str]) -> str:
    result = run_git(arguments)
    if result.returncode != 0:
        message = result.stderr.strip() or result.stdout.strip()
        raise RuntimeError(f"git {' '.join(arguments)} failed: {message}")
    return result.stdout.strip()


def package_summary() -> list[str]:
    return [
        "## Package state",
        "",
        "Generated from an extracted package without Git metadata. Review the diff after applying it to the existing clone.",
        "",
        "```bash",
        "git status --short",
        "git diff --stat",
        "git diff -- README.md",
        "```",
        "",
    ]


def worktree_summary() -> list[str]:
    status = git_output(["status", "--short"])
    stat = git_output(["diff", "--stat"])
    readme_diff = git_output(["diff", "--", "README.md"])
    lines = ["## Changed files", ""]
    lines.extend(f"- `{line}`" for line in status.splitlines()) if status else lines.append("- No working-tree changes detected.")
    lines.extend(["", "## Diff stat", "", "```text", stat or "No unstaged diff.", "```", ""])
    if readme_diff:
        lines.extend(["## README diff", "", "```diff", readme_diff[:12000], "```", ""])
    return lines


def main() -> int:
    lines = [
        "# Generated Special Profile Update Summary",
        "",
        "Generated by `scripts/write_update_summary.py`.",
        "",
    ]
    lines.extend(worktree_summary() if inside_git_worktree() else package_summary())
    lines.extend([
        "## Required review",
        "",
        "- Run `python scripts/portfolio_ci.py final-check`.",
        "- Confirm every public claim matches its evidence level.",
        "- Confirm private project material remains sanitized and NDA-safe.",
        "- Inspect the rendered README links and activity dates.",
        "- Review portfolio/discovered-projects.json; candidates must remain pending or explicitly ignored until approved.",
        "- Do not add screenshots, logs, or metrics without revision and privacy review.",
        "",
    ])
    SUMMARY_PATH.write_text("\n".join(lines), encoding="utf-8", newline="\n")
    print(f"Wrote {SUMMARY_PATH.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
